import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import {SidebarInset, SidebarProvider} from '@/components/ui/sidebar';
import {SiteHeader} from '@/components/site-header';
import {AppSidebar} from '@/components/app-sidebar';

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
      <div className="[--header-height:calc(theme(spacing.14))]">
          <SidebarProvider className="flex flex-col">
              <SiteHeader />
              <div className="flex flex-1">
                  <AppSidebar />
                  <SidebarInset>
                      <div className="flex flex-1 flex-col gap-4 p-4">
                          <div className="min-h-[100vh] flex-1 rounded-xl bg-muted/50 md:min-h-min">
                              {children}
                          </div>
                      </div>
                  </SidebarInset>
              </div>
          </SidebarProvider>
      </div>
      </body>
    </html>
  );
}
